### ISSUE TITLE
LVL5 feature: migrate data if PVC gets full

### ISSUE THREAD

**Issue by durandom** [AICoE/kubeflow#2]
This is a placeholder issue for the LVL5 feature to be implemented.

* monitor the % free of the PVC of the user and pod
* when running out of space:
  * notify user
  * extend PVC 
  * migrate data

We have an ansible playbook for this already in the internal DH repo

**Comment by 4n4nd** [comment]
Migration of data to new PVC was implemented, but we will try to use PVC expanding which is available with the newer versions of Kubernetes and OpenShift.
@HumairAK
