### ISSUE TITLE
Monitor PVCs for Notebook pods

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/kubeflow#7]
In the reconciliation loop (notebook_controller.go), the pod status for the Notebook server is being monitored [here](https://github.com/AICoE/kubeflow/blob/master/components/notebook-controller/controllers/notebook_controller.go#L196). 
I was thinking, we should try monitoring the PVCs attached to the notebook pods right after [the pod is found](https://github.com/AICoE/kubeflow/blob/master/components/notebook-controller/controllers/notebook_controller.go#L207) and once we are successfully able to monitor the PVCs, we can move on to the scaling part.

@HumairAK @cfchase @vpavlin any thoughts?

**Comment by durandom** [comment]
@anishasthana can you comment on how we would monitor the PVC? Does it require an external dependency like prometheus and ceph?

**Comment by anishasthana** [comment]
How we currently monitor this is via Prometheus metrics from the kubelet. The relevant metrics:
`kubelet_volume_stats_used_bytes` and `kubelet_volume_stats_capacity_bytes`
It _might_ be possible for us to read this information directly from the kubelet somehow.

**Comment by 4n4nd** [comment]
We have implemented a simple `df` command being run on the Pod, the PVC is attached to but in the future we want to move to using the internal prometheus metrics.
