### ISSUE TITLE
Fix RBAC Generation so we don't need to use hand modified templates

### ISSUE THREAD

**Issue by 4n4nd** [AICoE/kubeflow#8]
There are RBAC groups specified in the [notebook-controller.go](https://github.com/AICoE/kubeflow/blob/master/components/notebook-controller/controllers/notebook_controller.go#L75), but the RBAC templates are not generated using `make manifest`.

1. We need to open an issue upstream for this to let them know something isn't working
2. Fix it and get it merged upstream

**Comment by HumairAK** [comment]
Merged upstream https://github.com/kubeflow/kubeflow/pull/5083
